### ISSUE TITLE
Binary operator precedence (< over +)

### ISSUE THREAD

**Issue by kamadorueda** [tree-sitter/tree-sitter-java#70] opened 2021-03-17 18:10 UTC
### Problem description

Hi guys, I've been using the library extensively and I think I've found a bug:

The following expression yields a boolean: `(1*1) + num > 5`,
it should be interpreted as `((1*1) + num) > 5`

as shown here:

![image](https://user-images.githubusercontent.com/47480384/111510587-ec1b2200-871b-11eb-9517-697f140218bd.png)

Whereas the library interprets the operation as (1*1) + (num > 5)
![image](https://user-images.githubusercontent.com/47480384/111510723-0c4ae100-871c-11eb-922c-eeb638353b17.png)

is this a matter of flipping the operator precedence here: https://github.com/tree-sitter/tree-sitter-java/blob/master/grammar.js#L13 ?

**Comment by aryx** [comment] 2021-03-19 08:50
seems like a dupe of https://github.com/tree-sitter/tree-sitter-java/issues/68
Could you fix also the priority of shift operators?

**Closed** 2021-04-08 22:27 UTC
